# .circleci/config.yml

version: 2.1

jobs:
  build:
    docker:
      - image: golang:latest

    working_directory: /go/src/github.com/niravraychura/todolist

    steps:
      - checkout

      # Install Go dependencies
      - run:
          name: Install dependencies
          command: go mod download

      # Build the Go application
      - run:
          name: Build application
          command: go build -o app .


  dockerize:
    docker:
      - image: docker:stable

    working_directory: /go/src/github.com/niravraychura/todolist

    steps:
      - checkout

      # Build Docker image
      - run:
          name: Build Docker image
          command: |
            docker build -t raychuranirav/todolist:$CIRCLE_BUILD_NUM .
            docker tag raychuranirav/todolist:$CIRCLE_BUILD_NUM raychuranirav/todolist:latest

      # Push Docker image to Docker Hub (optional)
     
      - setup_remote_docker
      - run:
           name: Push Docker image to Docker Hub
           command: |
             echo "$DOCKER_PAT" | docker login -u "$DOCKER_USERNAME" --password-stdin
             docker push raychuranirav/todolist:$CIRCLE_BUILD_NUM
             docker push raychuranirav/todolist:latest

workflows:
  version: 2
  build_and_dockerize:
    jobs:
      - build
      - dockerize:
          requires:
            - build
          filters:
            branches:
              only: main
